FROM python:3.12.3-alpine
LABEL MAINTAINER="BJ Dierkes <derks@datafolklabs.com>"
ENV PS1="\[\e[0;33m\]|> cement-py312 <| \[\e[1;35m\]\W\[\e[0m\] \[\e[0m\]# "

WORKDIR /src
RUN apk update \
    && apk add libmemcached-dev \
        gcc \
        musl-dev \
        cyrus-sasl-dev \
        zlib-dev \
        make \
        vim \
        bash \
        git \
        libffi \
        libffi-dev \
        openssl-dev \
        jq \
        pipx \
    && ln -sf /usr/bin/vim /usr/bin/vi
RUN pipx install pdm
ENV PATH="${PATH}:/root/.local/bin"
COPY . /src
COPY docker/vimrc /root/.vimrc
COPY docker/bashrc /root/.bashrc
RUN pdm install
CMD ["/bin/bash"]
