FROM python:3.6-alpine
MAINTAINER BJ Dierkes <derks@datafolklabs.com>
ENV PS1="\[\e[0;33m\]|> cement <| \[\e[1;35m\]\W\[\e[0m\] \[\e[0m\]\# "

WORKDIR /app
COPY requirements-dev.txt /app/
RUN apk update \
    && apk add libmemcached-dev \
        gcc \
        musl-dev \
        cyrus-sasl-dev \
        zlib-dev \
        make \
        vim \
    && ln -sf /usr/bin/vim /usr/bin/vi \
    && pip install --no-cache-dir -r requirements-dev.txt
COPY . /app
COPY docker/vimrc /root/.vimrc
RUN python setup.py develop
CMD ["/bin/ash"]
