FROM python:3.6-alpine
MAINTAINER {{ creator }} <{{ creator_email }}>
ENV PS1="\[\e[0;33m\]|> {{ label }} <| \[\e[1;35m\]\W\[\e[0m\] \[\e[0m\]# "

WORKDIR /app
COPY requirements.txt requirements-dev.txt /app/
RUN apk update \
    && apk add git make bash vim \
    && ln -sf /usr/bin/vim /usr/bin/vi \
    && pip install -r requirements-dev.txt \
    && rm -f /usr/local/lib/python3.6/site-packages/cement.egg-link \
    && cd src/cement \
    && python setup.py install \
    && cd /app \
    && rm -rf src/cement
COPY . /app
RUN python setup.py develop
CMD ["/bin/bash"]
